### PR TITLE
Fix #15

### LINKED ISSUE #15: 1.3.0 breaks compatiblity with `deno test` again
The 'graceful handling of interruptions' in the following commit 

https://github.com/deno-library/progress/commit/c7f01b296bae7420215b9b256d4426bcc74660a8

breaks `deno test` by leaking async ops: 

Bildschirmfoto 2022-11-07 um 22 57 03

I'm currently looking into it how to fix it.

### PR DESCRIPTION
**Pull request by bjesuiter**
This PR fixes: 
- the issue with leaking async ops with SIGINT listener (in both ProgressBar and MultiProgressBar) 
- the previous isTTY to hasStdout fix for MultiProgressBar 

It also includes: 
- a deno test file for multi.ts

### CODE REVIEW

**Comment by bjesuiter** [comment]
@fuxingZhang  I have one funny issue with this PR: 

When i run the `multi.test.ts`, it shows 2 of the three Progress-Bars like this: 
Bildschirmfoto 2022-11-08 um 01 51 32

I have to call `  bars.end();` at the end to finish the test without crashing. 
This makes the third timer appear at the end like this: 
Bildschirmfoto 2022-11-08 um 01 52 48

## My Problem 
I don't understand why the third timer behaves differently to the other twos, since the code is completely the same: 

```ts
  const promise1 = timer1.pipeTo(
    simpleCallbackTarget((progress) => {
      progressArray[0].completed = progress;
      renderProgress();
    }),
  );

  const promise2 = timer2.pipeTo(
    simpleCallbackTarget((progress) => {
      progressArray[1].completed = progress;
      renderProgress();
    }),
  );

  const promise3 = timer3.pipeTo(
    simpleCallbackTarget((progress) => {
      progressArray[2].completed = progress;
      renderProgress();
    }),
  );
```

Could you have a look into multi.test.ts and see why this happens?

**Comment by fuxingZhang** [comment]
Landed in [v1.3.1](https://github.com/deno-library/progress/releases/tag/v1.3.1)

**Comment by fuxingZhang** [comment]
I've fixed a [multi-bar rendering bug](https://github.com/deno-library/progress/commit/366f40df2a3b380a87d1ff1b51f87464713de78a)

**Comment by fuxingZhang** [comment]
> @fuxingZhang I have one funny issue with this PR:
> 
> When i run the `multi.test.ts`, it shows 2 of the three Progress-Bars like this: Bildschirmfoto 2022-11-08 um 01 51 32
> 
> I have to call ` bars.end();` at the end to finish the test without crashing. This makes the third timer appear at the end like this: Bildschirmfoto 2022-11-08 um 01 52 48
> 
> ## My Problem
> I don't understand why the third timer behaves differently to the other twos, since the code is completely the same:
> 
> ```ts
>   const promise1 = timer1.pipeTo(
>     simpleCallbackTarget((progress) => {
>       progressArray[0].completed = progress;
>       renderProgress();
>     }),
>   );
> 
>   const promise2 = timer2.pipeTo(
>     simpleCallbackTarget((progress) => {
>       progressArray[1].completed = progress;
>       renderProgress();
>     }),
>   );
> 
>   const promise3 = timer3.pipeTo(
>     simpleCallbackTarget((progress) => {
>       progressArray[2].completed = progress;
>       renderProgress();
>     }),
>   );
> ```
> 
> Could you have a look into multi.test.ts and see why this happens?

My test is ok. 

GIF 2022-11-8 11-44-02

It may be related to the operating system.
It is ok in the Windows Subsystem for Linux.

Using deno test on Windows systems will result in an error.
image

It is ok not to use the deno test.
image

**Comment by fuxingZhang** [comment]
I've fixed the [bug](https://github.com/deno-library/progress/commit/caaccd668181b6b0ca4153dc901ca9e19f10d2c5)

**If you have a good idea for this bug, happy to merge your code**

image

image

**Comment by bjesuiter** [comment]
Hmm, this windows bug is a tricky one, since many terminal emulators on windows don't report column width correctly, which is why deno thinks they are not real ttys. 

Have to look into it later :D

**Pull request merged**
