### PR TITLE
Support for custom writer and units template token

### PR DESCRIPTION
**Pull request by vectronic**
- feature: add support for passing custom `Deno.WriterSync` i.e. to allow output to `Deno.stderr`
- feature: add support for `:units` template field

### CODE REVIEW

**Comment by fuxingZhang** [comment]
There is already `:text`, why we need `:units`.

**Comment by vectronic** [comment]
I would like to be able to template like: text current/total units. E.g.   file.mp4  32/486MB

**Comment by fuxingZhang** [comment]
You can join all strings into text, `:text`= "file.mp4 32/486MB"
> I would like to be able to template like: text current/total units. E.g. file.mp4 32/486MB

**Comment by fuxingZhang** [comment]
Are there any practical use cases where data needs to be written to stderr?

**Comment by vectronic** [comment]
stderr: Pretty much every unix command line outputs the real output of the program on stdout so that you can pipe between commands. Any errors, logging or progress information are usually output on stderr.

units: understood on using :text but that kind of means that :completed and :total are no longer to be used or are redundant.

Feel free to reject the PR, I'm happy to use my fork for my purposes. I just thought it might be useful to you.

**Comment by fuxingZhang** [comment]
Stderr can be accepted. 
The principle is simplicity and ease of use.
`units:`  will not be accepted.

**Comment by vectronic** [comment]
Will relook at it

**Comment by fuxingZhang** [comment]
> Will relook at it

Thanks

**Pull request closed without merging**
